
@url = http://localhost:4400/api/accounts 


GET {{url}}/?limit=3&sortby=name&sortdir=desc HTTP/1.1


### get fifth accout
GET {{url}}/9 HTTP/1.1



### make a new account
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "name":"new",
    "budget":21332
}

### update the sixth account
PUT {{url}}/2 HTTP/1.1
Content-Type: application/json

{
    "name":"nwedo",
    "budget":213322
}

### delete the sixth account

DELETE  {{url}}/2 HTTP/1.1



